### ISSUE TITLE
Replay the policy?

### ISSUE THREAD

**Issue by hai-h-nguyen** [Yusufma03/DPFRL#1]
Is there any way to visualize the learned policy, probably from a saved file?

**Comment by Yusufma03** [comment]
Hi, the trained model will be saved in the log folder, please refer to [this line](https://github.com/Yusufma03/DPFRL/blob/e8b529acd70bfa58c4c4b27268915242abc8a892/code/main.py#L688). You can load it using load_state_dict function and replay the trained model. Please refer to [this tutorial](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for more details.
